### ISSUE TITLE
Migrate to Netlify

### ISSUE THREAD

**Issue by mithintv** [mithin888/wordle-tracker-api#1]
#### Tasks
- [x] Migrate to Netlify
- [x] Add environment variables
- [x] Update slack listener api
- [ ] Ensure database connection works
